# Generated by Django 5.0.6 on 2024-06-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('items', '0002_alter_item_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'category')},
        ),
    ]
