# Generated by Django 5.0.6 on 2024-06-12 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField(default=0, editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='items.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='suppliers.supplier')),
            ],
            options={
                'verbose_name_plural': 'Purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_quantity', models.FloatField(blank=True, null=True)),
                ('sale_quantity', models.FloatField(blank=True, null=True)),
                ('total_balance_quantity', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='items.item')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_purchases', to='transactions.purchase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['item'], name='transaction_item_id_54bcac_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier'], name='transaction_supplie_14e45a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['created_at'], name='transaction_created_7e5e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['item'], name='transaction_item_id_849ada_idx'),
        ),
    ]
