# Generated by Django 5.0.6 on 2024-06-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_delete_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_date',
        ),
    ]
