# Generated by Django 5.0.6 on 2024-06-13 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_sale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
