# Generated by Django 5.0.6 on 2024-06-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_sale_options_remove_sale_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
    ]
